# .github/workflows/rust-release.yml

name: Build and Release Rust Project

# 该工作流使用 workflow_dispatch 手动触发
on:
  workflow_dispatch:
    inputs:
      tag:
        description: '要创建和发布的 Tag，例如 v1.0.0'
        required: true
        type: string

# 设置环境变量，让 cargo 的输出带有颜色
env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-release:
    name: Build Linux Release (amd64)
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.get_project_name.outputs.project_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get project name
        id: get_project_name
        run: echo "project_name=$(grep '^name' Cargo.toml | head -n 1 | sed -e 's/name = "//' -e 's/"//')" >> $GITHUB_OUTPUT

      - name: Build release image
        run: |
          docker build . \
            --file docker/amd64/Dockerfile \
            --tag ${{ steps.get_project_name.outputs.project_name }}:release \
            --build-arg BUILD_PROFILE=release
      
      - name: Extract release artifact
        run: |
          mkdir -p artifacts
          docker run --rm --entrypoint cat ${{ steps.get_project_name.outputs.project_name }}:release /root/app > artifacts/${{ steps.get_project_name.outputs.project_name }}-linux-amd64

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64-release-binary
          path: artifacts/${{ steps.get_project_name.outputs.project_name }}-linux-amd64

  build-linux-debug:
    name: Build Linux Debug (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get project name
        id: get_project_name
        run: echo "project_name=$(grep '^name' Cargo.toml | head -n 1 | sed -e 's/name = "//' -e 's/"//')" >> $GITHUB_OUTPUT

      - name: Build debug image
        run: |
          docker build . \
            --file docker/amd64/Dockerfile \
            --tag ${{ steps.get_project_name.outputs.project_name }}:debug \
            --build-arg BUILD_PROFILE=debug

      - name: Extract debug artifact
        run: |
          mkdir -p artifacts
          docker run --rm --entrypoint cat ${{ steps.get_project_name.outputs.project_name }}:debug /root/app > artifacts/${{ steps.get_project_name.outputs.project_name }}-debug-linux-amd64
      
      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64-debug-binary
          path: artifacts/${{ steps.get_project_name.outputs.project_name }}-debug-linux-amd64

  build-windows-amd64-release:
    name: Build Windows Release (amd64)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get project name
        id: get_project_name
        run: |
          $projectName = (Get-Content Cargo.toml | Select-String -Pattern '^name' | Select-Object -First 1).Line -replace 'name = "', '' -replace '"', ''
          echo "project_name=$projectName" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Build with cargo
        run: cargo build --release
        shell: cmd
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64-release-binary
          path: target/release/${{ steps.get_project_name.outputs.project_name }}.exe

  build-windows-amd64-debug:
    name: Build Windows Debug (amd64)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get project name
        id: get_project_name
        run: |
          $projectName = (Get-Content Cargo.toml | Select-String -Pattern '^name' | Select-Object -First 1).Line -replace 'name = "', '' -replace '"', ''
          echo "project_name=$projectName" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Build with cargo
        run: cargo build
        shell: cmd
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64-debug-binary
          path: target/debug/${{ steps.get_project_name.outputs.project_name }}.exe
          
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: 
      - build-linux-release
      - build-linux-debug
      - build-windows-amd64-release
      - build-windows-amd64-debug
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            ## Release Notes
            - Statically linked Linux binaries (x86_64-musl).
            - Windows binaries (x86_64).
            - Includes both release and debug versions, built in parallel.
            - Linux version built via a reusable Dockerfile.

      - name: Upload Linux Release Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux-amd64-release-binary/${{ needs.build-linux-release.outputs.project_name }}-linux-amd64
          asset_name: ${{ needs.build-linux-release.outputs.project_name }}-linux-amd64

      - name: Upload Linux Debug Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux-amd64-debug-binary/${{ needs.build-linux-release.outputs.project_name }}-debug-linux-amd64
          asset_name: ${{ needs.build-linux-release.outputs.project_name }}-debug-linux-amd64

      - name: Upload Windows Release Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows-amd64-release-binary/${{ needs.build-linux-release.outputs.project_name }}.exe
          asset_name: ${{ needs.build-linux-release.outputs.project_name }}-windows-amd64.exe

      - name: Upload Windows Debug Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows-amd64-debug-binary/${{ needs.build-linux-release.outputs.project_name }}.exe
          asset_name: ${{ needs.build-linux-release.outputs.project_name }}-debug-windows-amd64.exe
